local devSub = menu.add_feature("#FF0000FF#DEV", "parent", apexStuff["root"].id)

menu.add_feature("GET INT-STAT VALUE", "action", devSub.id, function() 
    system.wait(300)
    local value = apexStuff["helpers"].getInput("STAT NAME", "", 30, 0)

    local piss = stats.stat_get_int(gameplay.get_hash_key(apexStuff["helpers"].getCurrentChar(false)..value), 0)
    menu.notify(tostring(piss))
end)
menu.add_feature("SET INT-STAT VALUE", "action", devSub.id, function() 
    -- stats.stat_set_u64(gameplay.get_hash_key(apexStuff["helpers"].getCurrentChar(false).."TOTAL_PLAYING_TIME"), 528035702983, 528035702983)

    local value = apexStuff["helpers"].getInput("value", "", 70, 0)
    stats.stat_set_int(gameplay.get_hash_key(apexStuff["helpers"].getCurrentChar(false).."NUM_THRESH_CROSSED_TODAY"), value, true)
end)
menu.add_feature("GET STRING-STAT VALUE", "action", devSub.id, function() 
    local value = apexStuff["helpers"].getInput("value", "", 70, 0)
    local piss = apexStuff["natives"].stats.stat_get_string(gameplay.get_hash_key(apexStuff["helpers"].getCurrentChar(false)..value), 0)
    menu.notify(tostring(piss)) 
end)
menu.add_feature("NATIVE TEST", "action", devSub.id, function() 
    local piss = native.call(0x76EF28DA05EA395A)
    menu.notify(tostring(piss))
end)
menu.add_feature("GET DATE TEST", "action", devSub.id, function() 
    --local piss = apexStuff["natives"].stats.stat_get_date(gameplay.get_hash_key(apexStuff["helpers"].getCurrentChar(false) .. "REPEAT_OFFENDER_1_TIME"), )
    --menu.notify(tostring(piss))
end)
menu.add_feature("GET BOOLEAN TEST", "action", devSub.id, function() 
    menu.notify(tostring(stats.stat_get_bool(gameplay.get_hash_key("MPPLY_LOW_REPEAT_OFFENDER_CAP"), 0)))
    menu.notify(tostring(stats.stat_get_bool(gameplay.get_hash_key("MPPLY_HIGH_REPEAT_OFFENDER_CAP"), 0)))
end)
menu.add_feature("SET FAV WEAPON", "action", devSub.id, function() 
    -- FAVORITE_WEAPON
    stats.stat_set_int(gameplay.get_hash_key(apexStuff["helpers"].getCurrentChar(false).."FAVORITE_WEAPON"), 600439132, true)
end)
menu.add_feature("SET FAV WEAPON HELDTIME", "action", devSub.id, function() 
    stats.stat_set_int(gameplay.get_hash_key(apexStuff["helpers"].getCurrentChar(false).."FAVORITE_WEAPON_HELDTIME"), 115200000, true)
end)